### ISSUE TITLE
Release plan for draft 5

### ISSUE THREAD

**Issue by JanTvrdik** [json-schema-org/json-schema-spec#23] opened 2016-04-21 16:51 UTC
* Is there some release plan / time schedule for draft 5?
* Who is working on this? Is this currently a personal project of @Acubed who self-appointed himself or are there more people involved?

**Comment by Acubed** [comment] 2016-04-21 17:22
There's no current deadline to publishing a new draft, but we're putting work into it at least every few days. The problem is many of the people who own the important resources are MIA, and we'd like to avoid a wholesale fork.

I don't even own the json-schema-org group, I'm apparently the only person whose membership is public. I also check GitHub every day, so that might explain my activity.

Rest assured, even without a published draft, we still exist as a community of software libraries that work towards interoperability, so there shouldn't be _too_ much of a problem unless you need to cite an RFC number (as an editor of another Internet-draft) or unless you depend on IANA registration of `application/schema+json`.

**Comment by Acubed** [comment] 2016-05-03 05:10
@JanTvrdik If this answers your question then I'll let you close the issue, I do think all the concerns you bring up are addressed by other issues already.

Thanks!

**Closed** 2016-05-03 08:48 UTC
