### ISSUE TITLE
Can we customise the schema validation error message

### ISSUE THREAD

**Issue by yasassri** [json-schema-org/json-schema-spec#1075] opened 2021-02-09 11:42 UTC
Can we do something like the below?
		```
"service_name": {
			"type": "string",
			"pattern": "^([0-9A-Za-z]+[-_\\s]?[0-9A-Za-z]+)+$"
                          **"errorMessage": "The service name is not valid. Take a step back."**
		},
```

**Comment by Relequestual** [comment] 2021-02-09 11:52
This is a duplicate of https://github.com/json-schema-org/json-schema-spec/issues/62
that was revived as https://github.com/json-schema-org/json-schema-spec/issues/396
and resolved for draft `2019-09` (aka "draft 8").

You can use the output result of a failed validation process (which contains the keywords locations) to then access the error message in your schema.

You will need to determine which subschema is applicable to your situation if multiple subschemas fail.

**Closed by Relequestual** 2021-02-09 11:52 UTC
