### ISSUE TITLE
Number serialization options

### ISSUE THREAD

**Issue by cyberphone** [json-schema-org/json-schema-spec#736] opened 2019-05-06 06:57 UTC
Related: https://github.com/json-schema-org/json-schema-spec/issues/361

In many places including in IETF standards like JOSE, `BigIntegers` are represented not only as JSON Strings, but as specifically encoded such:
https://tools.ietf.org/html/rfc7518#section-6.3.1

This also permits hassle-free, cross-platform JSON messaging since IEEE-754 remains an issue in JavaScript.

In fact, even an `int64` fails (loses data) using ECMAScript's `JSON.parse()` since IEEE-754 double precision only provides 53 bits of precision.

**Comment by handrews** [comment] 2019-05-06 16:19
This is a duplicate of #361.  We don't need any convincing on the utility of numbers encoded as strings.  As I have stated many times, we just need someone knowledgeable to step up and write a PR.  If you are willing to do that, please make a note in #361.

**Closed by handrews** 2019-05-06 16:19 UTC
