### ISSUE TITLE
What is "$ref" and how does it work?

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#514] opened 2017-11-28 21:18 UTC
The question of whether `$ref` behaves like inclusion or delegation has come up several times.  

* Inclusion would mean that the `$ref` object can be replaced with its target (in a lazily evaluated process).
* Delegation means that the target of the `$ref` is processed against the current instance location, and the "results" (boolean assertion outcome and optionally the collected annotations) of `$ref` are simply the results of the target schema.

## Inclusion

In its original form, `$ref` in draft-03 and in the separate JSON Reference I-D is explicitly defined as inclusion.  Implementations MAY choose to replace the reference object with its target.

There are some subtleties involved in replacement.  You definitely need to adjust the `$id` when you do the replacement or else base URIs get messed up.  Tools such as [JSON Schema Ref Parser](https://github.com/BigstickCarpet/json-schema-ref-parser) that "dereference" `$ref`s do just that.

You also need to deal with `$schema`, which (when the target is in a different schema document) can be different in the source and target schemas.  The obvious solution is to set `$schema` in the copied-over replacement, however @epoberezkin has observed that this conflicts with how non-schema instances work with meta-schemas.

We cannot make any assumption about instance documents.  A key feature of JSON Schema is that it works with plain old `application/json` documents.  There is no way for a plain JSON document to change what schema is used to process it.  Changing `$schema` in the middle of validating a schema against its meta-schema introduces behavior that is not possible with other instance documents.

## Delegation

With delegation, these problems do not exist.  Each subschema is evaluated in the context of its containing schema document, regardless of whether processing reached it from elsewhere in that same document or from a `$ref` in a separate document.  Since the processing is done per-document, each document can use a different `$schema`.

Results are returned in the form of a single overall boolean assertion outcome (so it doesn't matter to the referencing document what the assertions were or how they were processed) and optionally a set of annotation data (which is a set of name-value pairs of some sort).

The only subtlety is in combining data for the same annotation that appeared in both a local document subschema and a remote `$ref`'d document subschema.  However, this is easily addressed:  once the annotation data is "returned" across the `$ref`, it is combined with other annotation data by the rules of the schema containing the `$ref`.  This keeps all processing consistent within each schema document, such that the rules can change independently on each side (for instance if they are upgraded to a new draft at different times).

Another nice property of delegation (also from @epoberezkin) is that `$ref` can become a "normal" keyword that has assertion and/or annotation results that are combined with adjacent schema keywords just like everything else.

## Alternate approaches

***NOTE:** This section is about showing that it is possible to handle the limitations in other ways.  *Neither of these approaches is a serious proposal for recommendation!**

### An alternate approach to inclusion

The one use case that is not well-handled by delegation is that of packing multiple schema documents into a single distribution unit (file, resource, whatever).  There's some debate as to how valid or important this use case is, but it does come up.  This is only done by replacing specific non-cyclic `$ref`s, and does not involve trying to "dereference" all `$ref`s in the system.

For those who really want to do this, it occurs to me that there is another way to handle it:  [`data:` URIs](https://tools.ietf.org/html/rfc2397):

Let's say that this is our reference target:

```JSON
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "propertyNames": {"pattern": "^foo"}
}
```

Here we see how it can be inlined into a draft-04 schema using a `data:` URI:

```JSON
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "allOf": [{
        "$ref": "data:application/schema+json,%7B%22%24schema%22%3A%20%22http%3A//json-schema.org/draft-06/schema%23%22%2C%20%22propertyNames%22%3A%20%7B%22pattern%22%3A%20%22%5Efoo%22%7D%7D"
    }]
}
```

Of course this looks horrible and would never be suitable for human consumption.  But it would work.

I'm not seriously advocating this as a recommendation, but it does illustrate that the problem is solvable in the delegation model if you are willing to make some tradeoffs.

### An alternate way to change processing rules

The limitation of replacement is that changing `$schema` in the middle of a file make validating schemas against meta-schemas different from validating other instances against schemas, as we cannot specify a schema change mechanism for plain `application/json` instance documents.

However, we could extend the instance-to-schema linking process to allow associating an instance JSON Pointer with each linked schema.  For schemas-as-instances, this would be equivalent to setting `$schema` at the location identified by the JSON Pointer.

This would have to be done as a link attribute/media type parameter thing of some sort.  Like the `data:` URI solution, this gets ugly pretty quickly, and makes it more likely to hit HTTP header length limitations.

It's also arguably a lot harder to hold in one's head than simply saying that `$schema` is scoped to a JSON document rather than an individual schema object.  While the data URI alternative given above is ugly, the ugliness comes from a separate standard, and is purely opt-in.  Schema authors have to choose to use those URIs, and implementations would choose whether to support data URIs or not.

This approach of targeting different schemas at different portions of the instance would place a significant burden on all implementations.

## Conclusions

Based on this write-up, I am inclined to formalize `$ref` as delegation.  It is a more flexible model, and the technique for working around its limitations correctly restricts the burden of implementation to only those who choose to use or support it.  Inclusion is less flexible, and the workaround (if we did anything about it at all) is burdensome to all implementations.

**Comment by handrews** [comment] 2017-11-28 21:50
Another interesting concept is the one raised by @darrelmiller in https://github.com/OAI/OpenAPI-Specification/issues/556#issuecomment-335986661, which classifies `$ref` as a link serialization.

This would put make it somewhat like `<a href="...">` in HTML, as an untyped (or implicitly typed as it serves exactly one purpose) hyperlink.  That is consistent with the delegation approach, including the use of data URIs.

In the OpenAPI issue, there's some discussion of `title` and `description` as link attributes to distinguish them from any such fields in the target schema, with two different syntax possibilities.  I'm still intrigued by that idea, but I'm not as sure that it is necessary.  In particular, deferred keywords as proposed by #515 may provide a more general way to "override" such annotations across references.

**Comment by erayd** [comment] 2017-11-28 21:52
Regarding `$ref`, I feel strongly that this should be a delegation. This allows behaviors such as validating part of a document against an external schema, without needing to care which version of the spec that remote schema uses - as long as the validator supports it, it will work.

For the particular case of schema transformations, I think that there should be *no visibility whatsoever* inside the target schema for the purpose of transformation. It's essentially a function call. Schemas wishing to transform the target should use a different keyword for that purpose (e.g. `$include`, or something else that indicates the target is a source for patching).

**Comment by handrews** [comment] 2017-11-29 17:36
As a note for readers here, if you want to discuss @erayd's points about schema transformations, that is going on in #515, so please join the discussion _over there_.

I'd like to keep this issue focused on delegation vs inclusion (and in particular, see if anyone wants to advocate for inclusion as the sentiment so far is definitely trending towards delegation).

**Comment by epoberezkin** [comment] 2017-11-30 07:55
Two additional arguments for delegation:
1. "Lazy evaluation" of inclusion is counter to users' expectations. The inclusion model implies that you can produce a "final", "resolved" schema document. In general case it is either impossible (in case you limit the data representation to JSON) or requires self-referencing data-structures (that are not universally supported and more difficult to process when they are supported; also the situation when you cannot represent "resolved" JSON Schema in JSON feels very wrong).
2. Delegation model has better extension potential for the future, e.g. for parametrised schemas (https://github.com/json-schema-org/json-schema-spec/issues/322).

**Comment by handrews** [comment] 2017-12-02 18:36
@epoberezkin thanks for the comment.  I agree on the extensibility thing and #322.  I'm still not necessarily sold on that (or `$data`) but I think that sorting out this issue and #515 will help us decide on both of those.

**Comment by sam-at-github** [comment] 2017-12-04 02:36
Why is "lazy evaluation" associated to inclusion and not delegation either? Couldn't you do either lazily?

**Comment by sam-at-github** [comment] 2017-12-04 02:38
I also think lazily evaluating a schema is a stupid idea and an edge case that no really need or wants. I.e. just compile the schema first instead of lazily evaluating.

**Alternative**

JSON schema should be completely independent of JSON Ref, except to possibly require that JSON Refs shall be *resolved* prio to evaluation.

**Comment by erayd** [comment] 2017-12-04 02:43
@sam-at-github Lazy evaluation makes implementation of recursive schemas easy. That's not an edge case; recursive schemas are common.

Also, non-lazy evaluation necessarily implies the evaluation of lots of schema paths which may not be applicable to the document instance at hand. This is a significant waste of resources, particularly for complex schema definitions being run against a simple document.

**Comment by sam-at-github** [comment] 2017-12-04 02:58
>  That's not an edge case; recursive schemas are common.

Resolve / compile it to a native reference.

> Also, non-lazy evaluation necessarily implies the evaluation of lots of schema paths which may not be applicable to the document instance at hand. This is a significant waste of resources,

That's why you do it once - compile.

Just makes things **so much simpler** if JSON Ref is a independent standard and JSON Schema stacks on top just like TCP/IP etc.

Last time I checked in with JSON Schema spec was over a year ago. They were arguing about $ref then!

**Comment by erayd** [comment] 2017-12-04 03:21
@sam-at-github I think we may have been talking about two different things then. But my point still stands - whether you're evaluating it or compiling it, the end result is you're still following lots of schema branches that may not make sense to follow, particularly in the case of dynamically generated schema which may not be able to be compiled in advance, or non-compiling implementations.

Assuming compilation happens where practical in either case, what advantages does non-lazy handling of `$ref` bring, that makes it better than lazy?

**Comment by sam-at-github** [comment] 2017-12-04 03:31
> Assuming compilation happens where practical in either case, what advantages does non-lazy handling of $ref bring, that makes it better than lazy?

1. You verify that your refs actually resolve up front, instead of your validator blowing up when it tries to resolve a certain unusual doc hitting a broken ref.
2. It make this spec simpler. JSON Schema doesn't have to care about refs or how they are resolved. It just assumes they are, and JSON Schema authors can stop arguing about it ;).

**Comment by handrews** [comment] 2017-12-04 05:45
@sam-at-github 

> Resolve / compile it to a native reference.

This is a JSON Specification.  There are no native references.  For some implementations that will make sense, for some it will not.  But it's all irrelevant to the specification:  We work with JSON, and with the underlying data model of JSON.  That is all.

> You verify that your refs actually resolve up front, instead of your validator blowing up when it tries to resolve a certain unusual doc hitting a broken ref.

It's easy to statically pre-check that all `$ref` targets have been seen.  That has nothing to do with runtime lazy evaluation.

> You verify that your refs actually resolve up front, instead of your validator blowing up when it tries to resolve a certain unusual doc hitting a broken ref.

Putting complexity somewhere else doesn't make it go away.  Also, even when it was a separate specification, you still needed to perform lazy evaluation in the context of schemas.  Validating the meta-schema against itself requires this.  You don't even have to look far.

Even when  JSON Reference was separate, this was always a concern that had to be dealt with (from draft-pbryan-zyp-json-ref-03, the last separate I-D for JSON Reference):

>    Documents containing JSON References can be structured to resolve
   cyclically.  Implementations SHOULD include appropriate checks to
   prevent such structures from resulting in infinite recursion or
   iteration.

This has always been done by resolving in the context of the instance.  Your schema references may cycle, but given a finite instance document you will always find an end to the recursion.

-----

You haven't made a single compelling statement for your position.  You've just kind of dropped inhere and called us all stupid, and pointed out that it's easier to implement if it's less powerful.  Which is no surprise, but does absolutely nothing to address the many real-world uses of cyclic references and lazy evaluation.

I've worked with very large sets of schemas- there is no way that project could have possibly worked without lazily evaluated `$ref`.

I've also inherited a project that forbid schema authors from using any recursive `$ref`s so that they could dereference everything as a preprocessor.  It really didn't end well.  They ended up introducing another `$ref`-ish keyword that was evaluated after `$ref`.  So instead of a uniform flexible lazy evaluation system, they had a weird custom two-phase mess.

--------

Removing the very long-standing (pre-draft-04) lazy evaluation nature of `$ref` is absolutely not on the table as an option.

**Comment by sam-at-github** [comment] 2017-12-04 06:41
Didn't call you stupid ...

I'm arguing for inclusion as it makes dealing with refs outside of JSON schema and refs possible. I still think lazy evaluation is stupid. As long as it's not mandatory.

> Putting complexity somewhere else doesn't make it go away.

No, but it can certainly make things less complex.

**Comment by handrews** [comment] 2017-12-04 06:51
You still haven't made a case for how your approach solves all use cases.  You've just decided many of our use cases are unimportant.  You've asserted that things that you care about are easier (probably true) but haven't offered any alternatives for what the community as a whole needs.  I do not see this line of reasoning going anywhere.

**Comment by sam-at-github** [comment] 2017-12-04 06:59
Not claiming to solve all use cases. 

> The question of whether $ref behaves like inclusion or delegation has come up several times.
>
>    Inclusion would mean that the $ref object can be replaced with its target (in a lazily evaluated process).
>    Delegation means that the target of the $ref is processed against the current instance location, and the "results" (boolean assertion outcome and optionally the collected annotations) of $ref are simply the results of the target schema.

In response to this is [this](https://github.com/json-schema-org/json-schema-spec/issues/514#issuecomment-348873206).

**Comment by handrews** [comment] 2017-12-04 07:05
@sam-at-github any serious proposal needs to solve all use cases.  This thread seems done.

**Comment by sam-at-github** [comment] 2017-12-04 07:17
OK Fine ... but just to summarize my position:

  1. lazy is stupid but that is beside the point of this issue. Sorry to start a war.
  2. I prefer inclusion.

>  Tools such as JSON Schema Ref Parser that "dereference" $refs do just that.

This is exactly the crux of my argument. *Modularity*, and  *Separation of concerns*. An author of a JSON Schema implementation can re-use "JSON Schema Ref" or what ever de-refer lib they want.

**Comment by Relequestual** [comment] 2017-12-04 15:45
@sam-at-github if you prefer inclusion, then you should consider the fact that de-refernecing to native references is not something that's possible in all languages. This is a general specification that isn't language specific, and as such shouldn't create something that will be an issue for some languages.

**Comment by Relequestual** [comment] 2017-12-04 15:56
Some libraries allow for specifying to use inclusion, in the case of a few, simple, known schemas, where it will be faster and you know it will be 100% resolveable. I don't see any issue with this being something implementors can allow as non default behaviour. It's useful in my use case where I might have MANY JSON instances to validate, and I don't want an HTTP call for every validation call, and I know they fully resolve (because the schemas are mine).

Could we specify that implementors MAY do this, as long as they document the potential issues with doing so, and it MUST NOT be default behaviour?

**Comment by handrews** [comment] 2017-12-04 16:44
@Relequestual depending on exactly where we go with vocabularies and `$schema`, dereferencing ends up subject to quite a few caveats.  I have on objection to documenting what is and isn't a legal dereference somewhere, but I think just specifying the behavior and not the implementation is the right approach.

If an implementation realizes that it can produce the correct behavior through inlining, that's fine.  The point of this decision is that we've had proposals come up that will work with one behavior but not the other, so we need to pick which behavior we endorse.

This is similar to "flattening" `allOf`.  We don't make a point in the spec that you can do that, but it's actually a pretty safe transformation most of the time and there are tools that offer it.  So I don't think we should confuse the issue beyond making sure that our wording is about behavior and not implementation.

**Comment by handrews** [comment] 2017-12-05 03:37
@Relequestual actually, `allOf` flattening is pretty relevant here.

***IF*** the `$ref` target shares the same meta-schema, and if `$id` is adjusted accordingly, then when treating `$ref` as delegation (meaning that it simply produces the same result- validation outcome and annotation values- as its target), then

`{"pattern": "^foo", "$ref": "anotherfile"}`
can be "dereferenced" to
`{"pattern" : "^foo", "allOf": [{contents of "anotherfile" with appropriate "$id"}]}`

As in my last comment, I think this is more of a tutorial guide sort of thing rather than an "implementations MAY do this" sort of thing.  Informally, implementations can do any transformations that they want as long as the outcome is computably the same.

**Comment by gregsdennis** [comment] 2017-12-05 05:31
@Relequestual 

> This is a general specification that isn't language specific, and as such shouldn't create something that will be an issue for some languages.

It seems contradictory that JSON Schema can be language agnostic while considering the languages in which it's implemented.

**Comment by gregsdennis** [comment] 2017-12-05 05:42
Just to put in my vote, I am also in favor of inclusion, however I understand the necessity to define how `$id` and `$schema` are included/transformed with the ref object.

**Comment by sam-at-github** [comment] 2017-12-05 07:07
@Relequestual 

> you should consider the fact that de-refernecing to native references is not something that's possible in all languages. 

I know some languages don't support a native ref type, but struggle to see the barrier still. Python comes to mind - sort of, but I'm not convinced there is not a simple work around in any language actually supporting a de-serializing a JSON string into some native object type in the first place.

By "native ref" I'm not saying literal built-in ref type. For example consider:

    json_str = '{
      "a": { "$ref": "#/q" }, 
      "b": { "$ref": "#/r" }
      "q": "blah",
      "r": {}
    }'
    myDoc = deref_my_doc(json_str)

Now `myDoc.a` or `myDoc['a']` or `myDoc.get('a')` what ever has to give "blah". There doesn't have to be a literal native reference. Granted there is an ambiguity of whether `myDoc.a` actually is the same storage location as `myDoc.a`, but I think there are solutions to that. I won't work through here, but basically yeah I think `myDoc.b` and `myDoc.r` must ref the same object (storage location). Tentatively, whether myDoc.a and myDoc.q do can be implementation dependent IMO.

> This is a general specification that isn't language specific, and as such shouldn't create something that will be an issue for some languages.

"all languages must be supported" gets raised a bit. But what are the entry level requirements of a language to support JSON and JSON Schema exactly? There is two requirements for the above:

  1. The language must have an native object representation, such that it can deserialize a JSON string into this native format in the first place.
  2. Must support object references.

The above sort of hinges on the second requirement because it is literally impossible to de-ref a document with loops if it doesn't. But I don't of a language that supports requirement 1. and not 2.

**Comment by sam-at-github** [comment] 2017-12-05 07:10
@handrews 
> You also need to deal with $schema, which (when the target is in a different schema document) can be different in the source and target schemas.

Do you though? You don't if JSON Ref is a separate standard and doesn't know or care what "$schema" means :)

**Comment by erayd** [comment] 2017-12-05 07:22
@sam-at-github The other problem with separating `$ref` into a different standard is that with JSON schema it's not legal in every object container.

For example, this is not a reference - it's simply a property named `$ref`:
```JSON
{
    "properties": {
        "$ref": {
            "type": "integer"
        }
    }
}
```
A naive implementation of `$ref` as an independent standard would try to dereference that and fail. In order to *not* be naive, `$ref` needs to understand the JSON schema spec (because `properties` is not a schema; it's a named list of schemas). At that point, `$ref` might as well simply be *part* of the JSON schema spec, because it's not possible to separate the two.

> The language must have an native object representation, such that it can deserialize a JSON string into this native format in the first place.

You don't need a native object representation in order to work with objects (and JSON schema). C is an example of a language that does not, and it's quite possible to work with JSON schema using that, albeit a bit verbose.

**Comment by sam-at-github** [comment] 2017-12-05 07:56
> For example, this is not a reference - it's simply a property named $ref ...  A naive implementation of $ref as an independent standard would try to dereference that and fail.

Indeed it would. It's a $ref after all. Isn't it the same essential problem as special characters? Thats's been solved before. The generally accepted time tested solution to that escaping. My solution would be ~ "JSON Ref shall replace \$ref with $ref". No good?

> You don't need a native object representation in order to work with objects (and JSON schema). C is an example of a language that does not, and it's quite possible to work with JSON schema using that, albeit a bit verbose.

I was aware there was a C implementation. Almost mentioned it. I'm tripping up on the word "native". I would say what ever C is doing it's "native" since it de-serialized and C specific object representation what ever the hell it is.

**Comment by awwright** [comment] 2017-12-05 11:31
My understanding of $ref is it's functionally the same as simply transcluding - transparently including the referenced contents as many times as necessary. The only additional thing it does is that the URI base used for resolving URI References changes.

Perhaps we should re-evaluate how `$schema` works in this light, and permit `$schema` changes intra-document.

**Comment by handrews** [comment] 2017-12-05 18:45
@awwright see #431 for the last extensive discussion of inclusion vs delegation and `$schema`.  We @-mentioned you several times but it was while you weren't available and by the time you were back to being able to respond to things we'd closed it.

**Comment by handrews** [comment] 2017-12-05 20:08
> It seems contradictory that JSON Schema can be language agnostic while considering the languages in which it's implemented.

@gregsdennis language agnostic meaning that it should not do anything that either optimizes for specific languages or makes things difficult in them.  Due to the background of JSON it will always match JavaScript and languages with a similar data model better than other languages, but we should not make that compatibility issue any larger than it is.

**Comment by handrews** [comment] 2017-12-05 20:16
OK, somehow this issue, which is supposed to be about resolving ambiguities in the **current** definition of `$ref`, has turned into re-litigating things decided several drafts ago.

JSON Reference had to be evaluated lazily even when it was a separate spec.  The fact that some tools will do it as a pre-processor _when possible_ does not change that.

@sam-at-github no one who has been involved in writing the last several drafts is going to pay any attention to arguments that involve forbidding lazy evaluation because JSON Schema as a system would become useless to a huge percentage of the user community.  It wouldn't even be able to validate itself.  Therefore:

***Changing the lazy evaluation behavior of `$ref` is ABSOLUTELY NOT ON THE TABLE.***

Please do not take up further space in this issue on that topic.

**If** there's a serious, broad demand (not just two or three people) for a separate JSON Reference RFC, we can easily split it out later.  That is the least of our problems right now, so please also do not take up further space in this issue on that topic.

**Comment by sam-at-github** [comment] 2017-12-06 00:52
@awwright

> My understanding of $ref is it's functionally the same as simply transcluding - transparently substituting in the referenced contents as many times as necessary.

I'm pretty sure my understanding is the same ...

> Changing the lazy evaluation behavior of $ref is ABSOLUTELY NOT ON THE TABLE.

> Please do not take up further space in this issue on that topic.

Sorry but I never said I want lazy evaluation to be forbidden. I said I think it's stupid, and therefore obviously shouldn't be mandatory.

My major requirement is for *complete de-refing to always be possible (not mandatory) to complete independently of JSON Schema, and thus be doable as a pre processing step.*

For this reason I was in favor of inclusion over delegation, because delegation intertwines deref and validation.

Simple as that. Thank you.

**Comment by handrews** [comment] 2017-12-06 01:39
@sam-at-github I just don't understand what you are getting at, then.  It is not, in general, possible to completely de-reference schemas without an instance.  To dereference a schema with an instance in the general case, you need to do at least some validation work, if for no other reason than to figure out which subschemas apply and could be dereferenced and how deep the dereferencing must go.

It has never been the case that a JSON file with JSON references can always be converted to one without references.  That has nothing to do with whether it is a separate spec or not.  It wasn't possible in draft-04 (with a separate spec) and it's not possible now.

**Comment by awwright** [comment] 2017-12-06 02:19
@handrews I'm not sure what concrete effect this distinction would have, then. What's an example you can provide?

**Comment by gregsdennis** [comment] 2017-12-06 02:36
@awwright I can think of it from an implementation viewpoint where performance is a concern.

If an implementation has an `anyOf`, then only the `$ref`s up to one that passes will need to be resolved.

```json
{
    "anyOf": [
        {"$ref" : "http://reference.to/boolSchema"},
        {"$ref" : "http://reference.to/stringSchema"},
        {"$ref" : "http://reference.to/arraySchema"},
        {"$ref" : "http://reference.to/intSchema"}
    ]
}
```

If I attempt to validate a string, then the validator only needs to resolve up to the second schema.  While these technically *can* be resolved ahead of time, it makes sense not to.

That's the best I've got.  I can't think of a compelling example where `$ref`s *can't* be resolved as a preprocess step.

**Comment by sam-at-github** [comment] 2017-12-06 02:40
@handrews 
> I just don't understand what you are getting at 

I'm arguing in favor of inclusion semantics for $ref ... Beyond that, I'm arguing that JSON Ref should be handled independently of JSON Schema.

> It has never been the case that a JSON file with JSON references can always be converted to one without references. That has nothing to do with whether it is a separate spec or not. It wasn't possible in draft-04 (with a separate spec) and it's not possible now.
 
  1. It was ambiguous in v04. The whole JSON Ref schema upon which JSON Schema v4 relied is a bit of a joke, and needed to be fleshed out big time.
  2. Hence the whole bit "native" references and the fundamental requirements of the language supporting JSON Schema we were discussing over a few comments above. Please see this comment above - https://github.com/json-schema-org/json-schema-spec/issues/514#issuecomment-349215517

**Comment by handrews** [comment] 2017-12-06 02:44
@sam-at-github Let me try to narrow this down:  are you saying you want to preprocess the schema *before* you have an instance, or pre-process the schema in the context of an instance, such that the output schema (after preprocessing) is specific to the instance?

**Comment by sam-at-github** [comment] 2017-12-06 02:46
before

**Comment by handrews** [comment] 2017-12-06 02:47
> @handrews I'm not sure what concrete effect this distinction would have, then. What's an example you can provide?

@awwright which distinction?  Inclusion vs delegation?  Did you read #314?

@epoberezkin you need to get on this and defend your position because I'm worn out.  I have no idea what's going on anymore.  (seriously, how did we get to the point where _your_ position is the only one that makes sense to _me_?  Aren't we supposed to be arguing?  Someone make a note of the date)   :-D

**Comment by handrews** [comment] 2017-12-06 02:48
@sam-at-github OK, then fully dereference the draft-04 meta-schema and paste your preprocessor output here.  If you can't do that, what do you think we can change that would allow you to do so?

**Comment by sam-at-github** [comment] 2017-12-06 02:49
Nope can't do it. If you read the comments above I think you'd see that obviously I'm aware of this. I can paste you a binary dump of the language specific  deserialization though ...

**Comment by handrews** [comment] 2017-12-06 02:49
@gregsdennis 

> That's the best I've got, and this doesn't require a JSON instance to de-reference against. I can't think of a compelling example where $refs can't be resolved as a preprocess step.

The meta-schema?  Am I seriously out of my mind here?

**Comment by gregsdennis** [comment] 2017-12-06 02:50
@handrews easy... I'm new to this realm of discussion.

**Comment by handrews** [comment] 2017-12-06 02:51
@gregsdennis sorry, I apologize, I thought we'd discussed the meta-schema before and I just meant to reference that.  I was thinking of another response I guess :-(

**Comment by handrews** [comment] 2017-12-06 02:52
Also, I did not mean to imply that *you* think I'm out of my mind.  *I* am starting to think I'm out of my mind.

**Comment by awwright** [comment] 2017-12-06 02:53
@gregsdennis If the functionality is identical it doesn't matter how you optimize it.

**Comment by handrews** [comment] 2017-12-06 02:53
@sam-at-github I have **absolutely no idea** what you want.  You want to be able to dereference the set of non-cyclic schemas?  Nothing's stopping you for non-cyclic cases where `$schema` is the same on both ends.  You can do that when the theoretical model is delegation easily enough as well.

**Comment by handrews** [comment] 2017-12-06 02:57
@awwright ugh, I apologize I meant to ask if you'd read #431 not #314, although that is related as well.

**Comment by sam-at-github** [comment] 2017-12-06 02:57
What ever. Honestly, I think implementations should dive specs. This feels like specs trying to dirve implementations. If AJV and a couple of other big validators decide to go one way and **implement** that, that is bigger than what ever you say here. Then you can take that and spec it. I'm out. Good luck.

**Comment by erayd** [comment] 2017-12-06 02:59
@handrews No, you're making sense. This whole thread seems to have blown up a bit though.

@sam-at-github I understand where you're coming from in the context of resolving to a native recursive data structure. However, JSON has no such thing as a native pointer, or any kind - that's the gap that `$ref` is designed to fill for the purposes of JSON schema.

There is nothing stopping you from writing an implementation that preprocesses `$ref` into native pointers, in whatever language that implementation is written in. And that will work fine with recursive references. But you __cannot do this in pure JSON__, because the `$refs` __ARE__ the pointers. As such, the spec cannot possibly define dereferencing as an independent preprocessing step, because the output would be infinite (via direct inclusion). Because it's impossible for the `$ref` to be independently dereferenced in JSON, it cannot be specified separately.

Hopefully that helps...

**Comment by handrews** [comment] 2017-12-06 02:59
@sam-at-github this whole issue exists because @epoberezkin (author of AJV) implements `$ref` as delegation.

**Comment by erayd** [comment] 2017-12-06 03:00
> this whole issue exists because @epoberezkin (author of AJV) implements $ref as delegation.

For what it's worth, I also implement it as delegation. I find it much cleaner that way :-).

**Comment by gregsdennis** [comment] 2017-12-06 03:04
As do I.

**Comment by handrews** [comment] 2017-12-06 03:05
@erayd yeah, we've reached the point where I'm just coming across as a jerk and owe everyone (particularly @gregsdennis and @sam-at-github) an apology.  As I've mentioned to several people, temperamentally I'm not the ideal person to mediate the spec work, I'm just the person with time.

So, I do apologize to everyone for not slowing down and moderating my responses.  Maybe one day we'll get through a controversial issue where I don't end up owing anyone an apology.  Sadly still a work in progress (have I blown up #515 yet?  maybe there's hope there...)

**Comment by erayd** [comment] 2017-12-06 03:45
> On second thought, I actually replace the `$refs` with their target during evaluation, so would that be inclusion? But I also allow the defined `$schema` to be independent for `$refs`, so would that be delegation?

It could be either, depending on how you've done it. If:
 - All siblings of `$ref` are ignored
 - The reference target may define its own `$schema`, and
 - Any relative `$ref`s inside the target are rewritten to maintain correctness

...then it's probably delegation. Otherwise, it's a non-standard inclusion.

From an implentation perspective, it probably doesn't matter much how you actually go about achieving the end result, as long as it *conceptually* complies with the behavior mandated by the spec. If the end user can't tell the difference, then nobody (other than possibly future maintainers of your code) cares what kind of black box voodoo you cram into your implementation ;-).

**Comment by handrews** [comment] 2017-12-06 03:53
> From an implentation perspective, it probably doesn't matter much how you actually go about achieving the end result, as long as it conceptually complies with the behavior mandated by the spec.

Exactly!  If you're handling separate `$schema` values then it's acting like delegation.  As I mentioned further up, a lot of times you can "include" even in the delegation model.

The different `$schema` values are what make it so you can't output a valid "preprocessed" schema even if you can work with a slightly-invalid-but-well-behaved internal representation.

Since validating a schema against a meta-schema against itself by normal validation rules means you cannot change the meta-schema part of the way through the validation process.

Alternatively, if you respect non-root `$schema` values and allow the meta-schema to be changed during processing, you're now introducing behavior that cannot be accessed by regular JSON instance documents.  So validating schemas becomes a different process than validating non-schema JSON.

Unless, of course, we define that to be OK in the spec, but #431 was basically an argument over whether we should define it, and instead we decided to restrict `$schema` to the root.

**Comment by gregsdennis** [comment] 2017-12-06 04:05
So it seems I'm on the delegation side of the fence, and any inclusion in doing is merely an implementation detail.  At the end of the day, if I were to serializer my schema model back to JSON, even after using to validate, it would result in equivalent JSON to what it was at the outset.

However, once I validate a single JSON document, all references are set and are not re-dereferenced.  In that way, my validator is inclusive.

**Comment by epoberezkin** [comment] 2017-12-06 09:07
A fascinating read...

Inclusion model works with two caveats:
1. You need to support recursive and mutually recursive references. It is possible in two ways:
  a) using self-referencing data structures. It is possible in some languages and several people insisted that I do exactly that which I refused to do as it requires managing the stack and keeping track of the nodes that were visited. Instead ajv simply precompiles schemas into functions that delegates both problems to the language
  b) doing it lazily while validating the data - @sam-at-github all I wrote in my comment was that it is counter to everybody’s expectation.
2. Changing $ids to the absolute pointers to point to the same locations after the inclusion.

My whole motivation to create Ajv was that there was not a single JavaScript validator that was handling all recursive cases correctly. It’s probably just easier to reason about $ref as about delegation in general case, even though in simple cases inclusion is simpler to understand.

And I don’t defend “lazy” - quite the opposite, I just wrote that it’s not what people expect from inclusion. Also, the model that Ajv implements is static precompilation where $refs are inlined (i.e. included) if they don’t contain other $refs (although there is an option to prevent inclusion as in some rare cases it was still not working correctly) and compiled to function calls if they do. And function call is delegation.

**Comment by gregsdennis** [comment] 2017-12-06 19:43
When I first started my implementation, I understood that `$ref` is a pointer to a self-contained document. Any IDs or `$schema` declarations would be specific to that document.  If the linked document wanted to change the schema, no big deal. My implementation supports this.

As an example of a use case, suppose I have a schema that references a schema defined and maintained by someone else.

```json
{
  "$schema" : "[draft-04]"
  "properties" : {
    "myProp" : { "type" : "integer" },
    "otherProp" : { "$ref" : "http://reference.to/otherSchema" }
  }
}
```

As long as `otherSchema` is draft 4, there is no problem.  But suppose the maintainer of `otherSchema` decides to update their schema to draft 7 in order to take advantage of the if-then-else construct.

Based on my understanding, an inclusive validator would break upon finding the if-then-else construct in one of two ways:

1. It wouldn't recognize them as keywords and would fail to process them in that manner (more likely), or
2. It would recognize them as keywords, but not of draft 4, and would error out.

My schema shouldn't break in the validator because of this change by a third party.

**Comment by awwright** [comment] 2017-12-07 01:14
I'd like to see some test cases written up that test for the distinction. I'm not sure what that would look like exactly, can someone submit a PR to https://github.com/json-schema-org/JSON-Schema-Test-Suite ?

**Comment by gregsdennis** [comment] 2017-12-07 04:07
I have generated one, but I'm on my phone right now. I'll update with it when I get back on wifi.

**Comment by gregsdennis** [comment] 2017-12-07 05:34
@awwright 

It appears that the test suite is not configured to download the draft meta-schemas from their online sources.  The only way I know to resolve this is to copy them to the *remotes* directory.  Any ideas?

**Comment by awwright** [comment] 2017-12-07 08:16
@gregsdennis That's functionality that a validator should already have, or at least that's up to the implementation if the programmer needs to provide a copy of the meta schema.

This looks good, the remaining question is what would the expected result be if we use an "inclusion" versus a "delegation" model here?

**Comment by gregsdennis** [comment] 2017-12-07 09:05
@awwright from the discussion, I would guess that the "`$schema` is only allowed at the top-level" rule would break the inclusion model.  I expect that the delegation model would be fine with this.

**Comment by gregsdennis** [comment] 2017-12-08 23:15
As further evidence that `$ref` should support referencing different schema drafts, I submit http://schemastore.org/json/.

If, for example, I need to reference the [JSON Patch schema](http://json.schemastore.org/json-patch) and referencing different schema drafts is not supported, then I am *required* to write my schema using draft 4.  But this means that I can't take advantage of draft 6/7 features.  Also, if the maintainer of the JSON Patch schema decides to update it to another draft, then my schema breaks.

This interpretation creates an extremely brittle system, and inclusion requires this because the `$schema` keyword is only valid at the root of the schema, which means that you can't have a subschema be defined by a different draft.

Delegated referencing, however, naturally supports the above example because the target schema remains independent of the schema referring to it.

---

That said, there is nothing that says an implementation can't (within the context of the language in which it's written) copy an instance of the target schema into the referring schema.  The implementation simply must *interpret* that schema as being independent rather than a natural subschema.

**Comment by Relequestual** [comment] 2017-12-13 10:05
I've re-read this, skipping over my own comments, and eached the exact same conclusion.

I feel, we should specify:
Delegation as the default and expected behaviour.
Implementors MAY provide an interface to use inclusion, but MUST make people aware of the pitfalls / issues as per https://github.com/json-schema-org/json-schema-spec/issues/514#issuecomment-349577829, and have a mechanisum detect where a scham is not fully dereferenceable (like cyclic references) and throw errors in such situations.

As I said, this allows people with small schemas, that are fully known to them, to save time when doing batch validation of JSON.

**I would suggest no further comments, and a general thumbs up or down on this comment, and move forward to work on phrasing for making this clear.**

**Comment by Relequestual** [comment] 2017-12-14 11:40
=O As a rare event, I'm going to self assign and plan to make a Pull Request to solve this issue (unless anyone objects).

**Comment by sebilasse** [comment] 2018-01-16 12:35
I would also suggest to preserve the decorating properties `title` and `description`.
The spec says about these properties

> Both of these keywords can be used to decorate a user interface

But isn't the sense of a "decorator" that if you reuse references to decorate them differently.
Happens fairly often to me (e.g. producing forms w. JSON Schema).


http://json-schema.org/latest/json-schema-core.html#rfc.section.8 says:

> All other properties in a "$ref" object MUST be ignored.

could this become something like
"All other properties in a "$ref" object except "title" and "description" MUST be ignored" ?

**Comment by handrews** [comment] 2018-01-16 18:50
@sebilasse see #523

**Closed** 2018-06-30 18:05 UTC
Labels: Priority: High, Status: In Progress, Type: Question, core, re-use / addlProps
