### ISSUE TITLE
Link attributes in JSON Hyper-schema

### ISSUE THREAD

**Issue by awwright** [json-schema-org/json-schema-spec#7] opened 2015-08-19 17:53 UTC
The HTTP Link header, HTML, and Atom each define slightly different attributes on link relations. Things like hints at the target resource's media type, language, title, and other metadata that would otherwise require dereferencing the resource.

Perhaps JSON Schema should normatively reference these `link-extension`s or similar.

**Comment by yoshuawuyts** [comment] 2015-08-30 23:58
@Acubed can you post an example? I'm not sure what you mean by "normatively reference". Thanks!

**Comment by Acubed** [comment] 2015-08-31 00:00
@yoshuawuyts A normative reference, where compliance depends on also complying with the referenced spec, as opposed to a mere informative one.

https://www.ietf.org/iesg/statement/normative-informative.html

**Comment by yoshuawuyts** [comment] 2015-08-31 00:07
@Acubed ah, that makes sense. Thanks!

**Comment by Relequestual** [comment] 2017-01-05 11:05
I'm unclear what the issue is here. Could you further explain the problem you see?

**Comment by handrews** [comment] 2017-01-05 21:26
@Relequestual @awwright what I get from this is that we should explain what relations, if any, our Link Description Object fields have with link attributes defined by RFC 5988, HTML5, and/or Atom.  Some of ours agree with some of those, others do not.  And some of those do not entirely agree with each other.

It may be helpful to highlight our intentions for where we mean the functionality to be identical, and where we do not.

**Comment by handrews** [comment] 2017-09-02 15:17
I think that the abstract link model in RFC 5988bis makes describing compliance a bit more straightforward, with its distinction between the abstract model and serializations (including the HTTP link header).  Which means that "fixing" #377 will also address this issue, so I'll put it in the current milestone.

**Comment by handrews** [comment] 2017-10-20 20:03
Merged #427 which addressed #377 which, as noted above, means that this issue has been addressed as well.

**Closed by handrews** 2017-10-20 20:03 UTC
Labels: hypermedia, Priority: Medium, Status: In Progress, Type: Enhancement
